import React from "react";
import { useParams, Navigate } from "react-router-dom";
import ScanRes from "./ScanRes";
import SecurityReportDashboard from "./VulnReportPage";

const SCAN_DATA = {
  message: "ZAP scan completed successfully",
  target: "http://testphp.vulnweb.com",
  spiderScanId: "1",
  activeScanId: "0",
  totalFindings: 38,
  vulnerabilities: [
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "3",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10020",
      cweid: "1021",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "15",
      description:
        "The response does not protect against 'ClickJacking' attacks. It should include either Content-Security-Policy with 'frame-ancestors' directive or X-Frame-Options.",
      messageId: "13",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        OWASP_2021_A05:
          "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        POLICY_QA_STD: "",
        POLICY_PENTEST: "",
        "CWE-1021": "https://cwe.mitre.org/data/definitions/1021.html",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        "WSTG-v42-CLNT-09":
          "https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/11-Client-side_Testing/09-Testing_for_Clickjacking",
        OWASP_2017_A06:
          "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html",
      },
      reference:
        "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/X-Frame-Options",
      solution:
        "Modern Web browsers support the Content-Security-Policy and X-Frame-Options HTTP headers. Ensure one of them is set on all web pages returned by your site/app.\nIf you expect the page to be framed only by pages on your server (e.g. it's part of a FRAMESET) then you'll want to use SAMEORIGIN, otherwise if you never expect the page to be framed, you should use DENY. Alternatively consider implementing Content Security Policy's \"frame-ancestors\" directive.",
      alert: "Missing Anti-clickjacking Header",
      param: "x-frame-options",
      attack: "",
      name: "Missing Anti-clickjacking Header",
      risk: "Medium",
      id: "0",
      alertRef: "10020-1",
    },
    {
      nodeName: "http://testphp.vulnweb.com/sitemap.xml",
      sourceid: "3",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10038",
      cweid: "693",
      confidence: "High",
      sourceMessageId: 10,
      wascid: "15",
      description:
        "Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks. These attacks are used for everything from data theft to site defacement or distribution of malware. CSP provides a set of standard HTTP headers that allow website owners to declare approved sources of content that browsers should be allowed to load on that page — covered types are JavaScript, CSS, HTML frames, fonts, images and embeddable objects such as Java applets, ActiveX, audio and video files.",
      messageId: "10",
      inputVector: "",
      url: "http://testphp.vulnweb.com/sitemap.xml",
      tags: {
        OWASP_2021_A05:
          "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        POLICY_QA_STD: "",
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        "CWE-693": "https://cwe.mitre.org/data/definitions/693.html",
        OWASP_2017_A06:
          "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html",
      },
      reference:
        "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP\nhttps://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html\nhttps://www.w3.org/TR/CSP/\nhttps://w3c.github.io/webappsec-csp/\nhttps://web.dev/articles/csp\nhttps://caniuse.com/#feat=contentsecuritypolicy\nhttps://content-security-policy.com/",
      solution:
        "Ensure that your web server, application server, load balancer, etc. is configured to set the Content-Security-Policy header.",
      alert: "Content Security Policy (CSP) Header Not Set",
      param: "",
      attack: "",
      name: "Content Security Policy (CSP) Header Not Set",
      risk: "Medium",
      id: "1",
      alertRef: "10038-1",
    },
    {
      nodeName: "http://testphp.vulnweb.com/robots.txt",
      sourceid: "3",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10038",
      cweid: "693",
      confidence: "High",
      sourceMessageId: 12,
      wascid: "15",
      description:
        "Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks. These attacks are used for everything from data theft to site defacement or distribution of malware. CSP provides a set of standard HTTP headers that allow website owners to declare approved sources of content that browsers should be allowed to load on that page — covered types are JavaScript, CSS, HTML frames, fonts, images and embeddable objects such as Java applets, ActiveX, audio and video files.",
      messageId: "12",
      inputVector: "",
      url: "http://testphp.vulnweb.com/robots.txt",
      tags: {
        OWASP_2021_A05:
          "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        POLICY_QA_STD: "",
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        "CWE-693": "https://cwe.mitre.org/data/definitions/693.html",
        OWASP_2017_A06:
          "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html",
      },
      reference:
        "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP\nhttps://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html\nhttps://www.w3.org/TR/CSP/\nhttps://w3c.github.io/webappsec-csp/\nhttps://web.dev/articles/csp\nhttps://caniuse.com/#feat=contentsecuritypolicy\nhttps://content-security-policy.com/",
      solution:
        "Ensure that your web server, application server, load balancer, etc. is configured to set the Content-Security-Policy header.",
      alert: "Content Security Policy (CSP) Header Not Set",
      param: "",
      attack: "",
      name: "Content Security Policy (CSP) Header Not Set",
      risk: "Medium",
      id: "2",
      alertRef: "10038-1",
    },
    {
      nodeName: "http://testphp.vulnweb.com/sitemap.xml",
      sourceid: "3",
      other:
        "There is a chance that the highlight in the finding is on a value in the headers, versus the actual matched string in the response body.",
      method: "GET",
      evidence: "nginx/1.19.0",
      pluginId: "10009",
      cweid: "497",
      confidence: "High",
      sourceMessageId: 10,
      wascid: "13",
      description:
        "The server returned a version banner string in the response content. Such information leaks may allow attackers to further target specific issues impacting the product and version in use.",
      messageId: "10",
      inputVector: "",
      url: "http://testphp.vulnweb.com/sitemap.xml",
      tags: {
        OWASP_2021_A05:
          "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        POLICY_QA_STD: "",
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        OWASP_2017_A06:
          "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html",
        "WSTG-v42-INFO-02":
          "https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server",
        "CWE-497": "https://cwe.mitre.org/data/definitions/497.html",
      },
      reference:
        "https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/",
      solution:
        'Configure the server to prevent such information leaks. For example:\nUnder Tomcat this is done via the "server" directive and implementation of custom error pages.\nUnder Apache this is done via the "ServerSignature" and "ServerTokens" directives.',
      alert: "In Page Banner Information Leak",
      param: "",
      attack: "",
      name: "In Page Banner Information Leak",
      risk: "Low",
      id: "3",
      alertRef: "10009",
    },
    {
      nodeName: "http://testphp.vulnweb.com/robots.txt",
      sourceid: "3",
      other:
        "There is a chance that the highlight in the finding is on a value in the headers, versus the actual matched string in the response body.",
      method: "GET",
      evidence: "nginx/1.19.0",
      pluginId: "10009",
      cweid: "497",
      confidence: "High",
      sourceMessageId: 12,
      wascid: "13",
      description:
        "The server returned a version banner string in the response content. Such information leaks may allow attackers to further target specific issues impacting the product and version in use.",
      messageId: "12",
      inputVector: "",
      url: "http://testphp.vulnweb.com/robots.txt",
      tags: {
        OWASP_2021_A05:
          "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        POLICY_QA_STD: "",
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        OWASP_2017_A06:
          "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html",
        "WSTG-v42-INFO-02":
          "https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server",
        "CWE-497": "https://cwe.mitre.org/data/definitions/497.html",
      },
      reference:
        "https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/",
      solution:
        'Configure the server to prevent such information leaks. For example:\nUnder Tomcat this is done via the "server" directive and implementation of custom error pages.\nUnder Apache this is done via the "ServerSignature" and "ServerTokens" directives.',
      alert: "In Page Banner Information Leak",
      param: "",
      attack: "",
      name: "In Page Banner Information Leak",
      risk: "Low",
      id: "4",
      alertRef: "10009",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "3",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10038",
      cweid: "693",
      confidence: "High",
      sourceMessageId: 13,
      wascid: "15",
      description:
        "Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks. These attacks are used for everything from data theft to site defacement or distribution of malware. CSP provides a set of standard HTTP headers that allow website owners to declare approved sources of content that browsers should be allowed to load on that page — covered types are JavaScript, CSS, HTML frames, fonts, images and embeddable objects such as Java applets, ActiveX, audio and video files.",
      messageId: "13",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        OWASP_2021_A05:
          "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        POLICY_QA_STD: "",
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        "CWE-693": "https://cwe.mitre.org/data/definitions/693.html",
        OWASP_2017_A06:
          "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html",
      },
      reference:
        "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP\nhttps://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html\nhttps://www.w3.org/TR/CSP/\nhttps://w3c.github.io/webappsec-csp/\nhttps://web.dev/articles/csp\nhttps://caniuse.com/#feat=contentsecuritypolicy\nhttps://content-security-policy.com/",
      solution:
        "Ensure that your web server, application server, load balancer, etc. is configured to set the Content-Security-Policy header.",
      alert: "Content Security Policy (CSP) Header Not Set",
      param: "",
      attack: "",
      name: "Content Security Policy (CSP) Header Not Set",
      risk: "Medium",
      id: "5",
      alertRef: "10038-1",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "3",
      other: "",
      method: "GET",
      evidence: "nginx/1.19.0",
      pluginId: "10036",
      cweid: "497",
      confidence: "High",
      sourceMessageId: 13,
      wascid: "13",
      description:
        'The web/application server is leaking version information via the "Server" HTTP response header. Access to such information may facilitate attackers identifying other vulnerabilities your web/application server is subject to.',
      messageId: "13",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        OWASP_2021_A05:
          "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        POLICY_QA_STD: "",
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        OWASP_2017_A06:
          "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html",
        "WSTG-v42-INFO-02":
          "https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server",
        "CWE-497": "https://cwe.mitre.org/data/definitions/497.html",
      },
      reference:
        "https://httpd.apache.org/docs/current/mod/core.html#servertokens\nhttps://learn.microsoft.com/en-us/previous-versions/msp-n-p/ff648552(v=pandp.10)\nhttps://www.troyhunt.com/shhh-dont-let-your-response-headers/",
      solution:
        'Ensure that your web server, application server, load balancer, etc. is configured to suppress the "Server" header or provide generic details.',
      alert:
        'Server Leaks Version Information via "Server" HTTP Response Header Field',
      param: "",
      attack: "",
      name: 'Server Leaks Version Information via "Server" HTTP Response Header Field',
      risk: "Low",
      id: "6",
      alertRef: "10036-2",
    },
    {
      nodeName: "http://testphp.vulnweb.com/sitemap.xml",
      sourceid: "3",
      other: "",
      method: "GET",
      evidence: "nginx/1.19.0",
      pluginId: "10036",
      cweid: "497",
      confidence: "High",
      sourceMessageId: 10,
      wascid: "13",
      description:
        'The web/application server is leaking version information via the "Server" HTTP response header. Access to such information may facilitate attackers identifying other vulnerabilities your web/application server is subject to.',
      messageId: "10",
      inputVector: "",
      url: "http://testphp.vulnweb.com/sitemap.xml",
      tags: {
        OWASP_2021_A05:
          "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        POLICY_QA_STD: "",
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        OWASP_2017_A06:
          "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html",
        "WSTG-v42-INFO-02":
          "https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server",
        "CWE-497": "https://cwe.mitre.org/data/definitions/497.html",
      },
      reference:
        "https://httpd.apache.org/docs/current/mod/core.html#servertokens\nhttps://learn.microsoft.com/en-us/previous-versions/msp-n-p/ff648552(v=pandp.10)\nhttps://www.troyhunt.com/shhh-dont-let-your-response-headers/",
      solution:
        'Ensure that your web server, application server, load balancer, etc. is configured to suppress the "Server" header or provide generic details.',
      alert:
        'Server Leaks Version Information via "Server" HTTP Response Header Field',
      param: "",
      attack: "",
      name: 'Server Leaks Version Information via "Server" HTTP Response Header Field',
      risk: "Low",
      id: "7",
      alertRef: "10036-2",
    },
    {
      nodeName: "http://testphp.vulnweb.com/robots.txt",
      sourceid: "3",
      other: "",
      method: "GET",
      evidence: "nginx/1.19.0",
      pluginId: "10036",
      cweid: "497",
      confidence: "High",
      sourceMessageId: 12,
      wascid: "13",
      description:
        'The web/application server is leaking version information via the "Server" HTTP response header. Access to such information may facilitate attackers identifying other vulnerabilities your web/application server is subject to.',
      messageId: "12",
      inputVector: "",
      url: "http://testphp.vulnweb.com/robots.txt",
      tags: {
        OWASP_2021_A05:
          "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        POLICY_QA_STD: "",
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        OWASP_2017_A06:
          "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html",
        "WSTG-v42-INFO-02":
          "https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server",
        "CWE-497": "https://cwe.mitre.org/data/definitions/497.html",
      },
      reference:
        "https://httpd.apache.org/docs/current/mod/core.html#servertokens\nhttps://learn.microsoft.com/en-us/previous-versions/msp-n-p/ff648552(v=pandp.10)\nhttps://www.troyhunt.com/shhh-dont-let-your-response-headers/",
      solution:
        'Ensure that your web server, application server, load balancer, etc. is configured to suppress the "Server" header or provide generic details.',
      alert:
        'Server Leaks Version Information via "Server" HTTP Response Header Field',
      param: "",
      attack: "",
      name: 'Server Leaks Version Information via "Server" HTTP Response Header Field',
      risk: "Low",
      id: "8",
      alertRef: "10036-2",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "3",
      other:
        'This issue still applies to error type pages (401, 403, 500, etc.) as those pages are often still affected by injection issues, in which case there is still concern for browsers sniffing pages away from their actual content type.\nAt "High" threshold this scan rule will not alert on client or server error responses.',
      method: "GET",
      evidence: "",
      pluginId: "10021",
      cweid: "693",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "15",
      description:
        "The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'. This allows older versions of Internet Explorer and Chrome to perform MIME-sniffing on the response body, potentially causing the response body to be interpreted and displayed as a content type other than the declared content type. Current (early 2014) and legacy versions of Firefox will use the declared content type (if one is set), rather than performing MIME-sniffing.",
      messageId: "13",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        OWASP_2021_A05:
          "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        POLICY_QA_STD: "",
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        "CWE-693": "https://cwe.mitre.org/data/definitions/693.html",
        OWASP_2017_A06:
          "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html",
      },
      reference:
        "https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/gg622941(v=vs.85)\nhttps://owasp.org/www-community/Security_Headers",
      solution:
        "Ensure that the application/web server sets the Content-Type header appropriately, and that it sets the X-Content-Type-Options header to 'nosniff' for all web pages.\nIf possible, ensure that the end user uses a standards-compliant and modern web browser that does not perform MIME-sniffing at all, or that can be directed by the web application/web server to not perform MIME-sniffing.",
      alert: "X-Content-Type-Options Header Missing",
      param: "x-content-type-options",
      attack: "",
      name: "X-Content-Type-Options Header Missing",
      risk: "Low",
      id: "9",
      alertRef: "10021",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "3",
      other: "",
      method: "GET",
      evidence: "X-Powered-By: PHP/5.6.40-38+ubuntu20.04.1+deb.sury.org+1",
      pluginId: "10037",
      cweid: "497",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "13",
      description:
        'The web/application server is leaking information via one or more "X-Powered-By" HTTP response headers. Access to such information may facilitate attackers identifying other frameworks/components your web application is reliant upon and the vulnerabilities such components may be subject to.',
      messageId: "13",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        OWASP_2021_A01:
          "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
        "WSTG-v42-INFO-08":
          "https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/01-Information_Gathering/08-Fingerprint_Web_Application_Framework",
        POLICY_QA_STD: "",
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        OWASP_2017_A03:
          "https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure.html",
        "CWE-497": "https://cwe.mitre.org/data/definitions/497.html",
      },
      reference:
        "https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/01-Information_Gathering/08-Fingerprint_Web_Application_Framework\nhttps://www.troyhunt.com/shhh-dont-let-your-response-headers/",
      solution:
        'Ensure that your web server, application server, load balancer, etc. is configured to suppress "X-Powered-By" headers.',
      alert:
        'Server Leaks Information via "X-Powered-By" HTTP Response Header Field(s)',
      param: "",
      attack: "",
      name: 'Server Leaks Information via "X-Powered-By" HTTP Response Header Field(s)',
      risk: "Low",
      id: "10",
      alertRef: "10037",
    },
    {
      nodeName: "https://testphp.vulnweb.com",
      sourceid: "1",
      other:
        "Failed to connect.\nZAP attempted to connect via: https://testphp.vulnweb.com",
      method: "GET",
      evidence: "",
      pluginId: "10106",
      cweid: "311",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "4",
      description: "The site is only served under HTTP and not HTTPS.",
      messageId: "40",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        OWASP_2021_A05:
          "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        POLICY_QA_FULL: "",
        POLICY_PENTEST: "",
        OWASP_2017_A06:
          "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html",
        "WSTG-v42-CRYP-03":
          "https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels",
        "CWE-311": "https://cwe.mitre.org/data/definitions/311.html",
      },
      reference:
        "https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html\nhttps://letsencrypt.org/",
      solution: "Configure your web or application server to use SSL (https).",
      alert: "HTTP Only Site",
      param: "",
      attack: "",
      name: "HTTP Only Site",
      risk: "Medium",
      id: "11",
      alertRef: "10106",
    },
    {
      nodeName: "http://testphp.vulnweb.com/sitemap.xml",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 10,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "106",
      inputVector: "",
      url: "http://testphp.vulnweb.com/sitemap.xml",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack: "Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "12",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "109",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack: "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "13",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/sitemap.xml",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 10,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "112",
      inputVector: "",
      url: "http://testphp.vulnweb.com/sitemap.xml",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "14",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/sitemap.xml",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 10,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "114",
      inputVector: "",
      url: "http://testphp.vulnweb.com/sitemap.xml",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack: "msnbot/1.1 (+http://search.msn.com/msnbot.htm)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "15",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/robots.txt",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 12,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "116",
      inputVector: "",
      url: "http://testphp.vulnweb.com/robots.txt",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack: "Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "16",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/sitemap.xml",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 10,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "118",
      inputVector: "",
      url: "http://testphp.vulnweb.com/sitemap.xml",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "17",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/sitemap.xml",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 10,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "121",
      inputVector: "",
      url: "http://testphp.vulnweb.com/sitemap.xml",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "18",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/robots.txt",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 12,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "123",
      inputVector: "",
      url: "http://testphp.vulnweb.com/robots.txt",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "19",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/sitemap.xml",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 10,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "125",
      inputVector: "",
      url: "http://testphp.vulnweb.com/sitemap.xml",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (iPhone; CPU iPhone OS 8_0_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12A366 Safari/600.1.4",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "20",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "128",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack: "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "21",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/robots.txt",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 12,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "129",
      inputVector: "",
      url: "http://testphp.vulnweb.com/robots.txt",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack: "msnbot/1.1 (+http://search.msn.com/msnbot.htm)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "22",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/sitemap.xml",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 10,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "131",
      inputVector: "",
      url: "http://testphp.vulnweb.com/sitemap.xml",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/91.0",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "23",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "134",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack: "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "24",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/robots.txt",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 12,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "136",
      inputVector: "",
      url: "http://testphp.vulnweb.com/robots.txt",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "25",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/robots.txt",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 12,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "138",
      inputVector: "",
      url: "http://testphp.vulnweb.com/robots.txt",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "26",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "140",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack: "Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "27",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/robots.txt",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 12,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "142",
      inputVector: "",
      url: "http://testphp.vulnweb.com/robots.txt",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (iPhone; CPU iPhone OS 8_0_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12A366 Safari/600.1.4",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "28",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "144",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3739.0 Safari/537.36 Edg/75.0.109.0",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "29",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "146",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "30",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com/robots.txt",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 12,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "148",
      inputVector: "",
      url: "http://testphp.vulnweb.com/robots.txt",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/91.0",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "31",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "151",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack: "msnbot/1.1 (+http://search.msn.com/msnbot.htm)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "32",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "153",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "33",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "155",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "34",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "157",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (iPhone; CPU iPhone OS 8_0_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12A366 Safari/600.1.4",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "35",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "159",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/91.0",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "36",
      alertRef: "10104",
    },
    {
      nodeName: "http://testphp.vulnweb.com",
      sourceid: "1",
      other: "",
      method: "GET",
      evidence: "",
      pluginId: "10104",
      cweid: "0",
      confidence: "Medium",
      sourceMessageId: 13,
      wascid: "0",
      description:
        "Check for differences in response based on fuzzed User Agent (eg. mobile sites, access as a Search Engine Crawler). Compares the response statuscode and the hashcode of the response body with the original response.",
      messageId: "161",
      inputVector: "",
      url: "http://testphp.vulnweb.com",
      tags: {
        POLICY_PENTEST: "",
        SYSTEMIC:
          "https://www.zaproxy.org/docs/desktop/addons/common-library/alerttags/#systemic",
        CUSTOM_PAYLOADS: "",
      },
      reference: "https://owasp.org/wstg",
      solution: "",
      alert: "User Agent Fuzzer",
      param: "Header User-Agent",
      attack:
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
      name: "User Agent Fuzzer",
      risk: "Informational",
      id: "37",
      alertRef: "10104",
    },
  ],
};

const data = {
  target: "https://openai.com",
  ip_address: "172.64.154.211",
  scan_time: "2026-01-29T22:13:42.983515",
  duration: 97.29712748527527,
  grade: "B",
  risk_score: 26,
  total_vulnerabilities: 6,
  port_results: {
    open_ports: [
      {
        port: 80,
        service: "HTTP",
        risk: "low",
        banner:
          "HTTP/1.1 400 Bad Request\r\nDate: Thu, 29 Jan 2026 16:43:45 GMT\r\nContent-Length: 68\r\nConnection: close\r\nCache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0\r",
      },
      {
        port: 443,
        service: "HTTPS",
        risk: "low",
        banner: "",
      },
    ],
    summary: {
      total_scanned: 24,
      open_ports: 2,
      risk_breakdown: {
        critical: 0,
        high: 0,
        medium: 0,
        low: 2,
      },
      critical_findings: [],
      high_findings: [],
    },
  },
  ssl_results: {
    has_ssl: true,
    is_valid: false,
    grade: "C",
    version: "TLSv1.3",
    issuer: "WE1",
    expires: "2026-04-23",
    days_until_expiry: 83,
    vulnerabilities: [],
  },
  header_results: {
    score: 73,
    grade: "B",
    summary: "6 present, 0 partial, 2 missing out of 8 headers",
    missing_headers: [
      {
        name: "Content-Security-Policy",
        importance: "critical",
        description: "Prevents XSS and injection attacks",
        weight: 20,
      },
      {
        name: "X-XSS-Protection",
        importance: "low",
        description: "Legacy XSS filter (deprecated in modern browsers)",
        weight: 5,
      },
    ],
    present_headers: [
      {
        name: "Strict-Transport-Security",
        value: "max-age=31536000; includeSubDomains; preload",
        importance: "critical",
        weight: 20,
        is_partial: false,
      },
      {
        name: "X-Frame-Options",
        value: "SAMEORIGIN",
        importance: "high",
        weight: 15,
        is_partial: false,
      },
      {
        name: "X-Content-Type-Options",
        value: "nosniff",
        importance: "high",
        weight: 15,
        is_partial: false,
      },
      {
        name: "Referrer-Policy",
        value: "same-origin",
        importance: "medium",
        weight: 10,
        is_partial: false,
      },
      {
        name: "Permissions-Policy",
        value:
          "accelerometer=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=",
        importance: "medium",
        weight: 10,
        is_partial: false,
      },
      {
        name: "Cross-Origin-Opener-Policy",
        value: "same-origin",
        importance: "low",
        weight: 5,
        is_partial: false,
      },
    ],
    partial_headers: [],
    information_disclosure: [
      {
        header: "server",
        value: "cloudflare",
        description: "Server software",
        penalty: 2,
      },
    ],
    other_issues: [],
  },
  vuln_results: {
    vulnerabilities: [],
    sensitive_files: [
      {
        file: "robots.txt",
        url: "https://openai.com/robots.txt",
        status: 200,
        size: 98,
        risk: "medium",
      },
      {
        file: "sitemap.xml",
        url: "https://openai.com/sitemap.xml",
        status: 200,
        size: 1545,
        risk: "medium",
      },
    ],
    risk_score: 10,
  },
  dir_results: {
    found_directories: [
      {
        path: "administrator",
        url: "https://openai.com/administrator",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "login",
        url: "https://openai.com/login",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "admin",
        url: "https://openai.com/admin",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "phpmyadmin",
        url: "https://openai.com/phpmyadmin",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "panel",
        url: "https://openai.com/panel",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "conf",
        url: "https://openai.com/conf",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "api",
        url: "https://openai.com/api",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "config",
        url: "https://openai.com/config",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "adminer",
        url: "https://openai.com/adminer",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "api/v2",
        url: "https://openai.com/api/v2",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "settings",
        url: "https://openai.com/settings",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "old",
        url: "https://openai.com/old",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "graphql",
        url: "https://openai.com/graphql",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "test",
        url: "https://openai.com/test",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "development",
        url: "https://openai.com/development",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "rest",
        url: "https://openai.com/rest",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "staging",
        url: "https://openai.com/staging",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "api/v1",
        url: "https://openai.com/api/v1",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "wp-admin",
        url: "https://openai.com/wp-admin",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "upload",
        url: "https://openai.com/upload",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "manager",
        url: "https://openai.com/manager",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "configuration",
        url: "https://openai.com/configuration",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "uploads",
        url: "https://openai.com/uploads",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "files",
        url: "https://openai.com/files",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "secret",
        url: "https://openai.com/secret",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "media",
        url: "https://openai.com/media",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "dev",
        url: "https://openai.com/dev",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "backup",
        url: "https://openai.com/backup",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: ".env",
        url: "https://openai.com/.env",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "documents",
        url: "https://openai.com/documents",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "dashboard",
        url: "https://openai.com/dashboard",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "internal",
        url: "https://openai.com/internal",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: ".git",
        url: "https://openai.com/.git",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "private",
        url: "https://openai.com/private",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: ".htpasswd",
        url: "https://openai.com/.htpasswd",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "assets",
        url: "https://openai.com/assets",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "wp-content",
        url: "https://openai.com/wp-content",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: ".svn",
        url: "https://openai.com/.svn",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "wp-includes",
        url: "https://openai.com/wp-includes",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "hidden",
        url: "https://openai.com/hidden",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "cgi-bin",
        url: "https://openai.com/cgi-bin",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "static",
        url: "https://openai.com/static",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "includes",
        url: "https://openai.com/includes",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "js",
        url: "https://openai.com/js",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "scripts",
        url: "https://openai.com/scripts",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "testing",
        url: "https://openai.com/testing",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "images",
        url: "https://openai.com/images",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "logs",
        url: "https://openai.com/logs",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "server-status",
        url: "https://openai.com/server-status",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "error_log",
        url: "https://openai.com/error_log",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "css",
        url: "https://openai.com/css",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "server-info",
        url: "https://openai.com/server-info",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "mysql",
        url: "https://openai.com/mysql",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "bin",
        url: "https://openai.com/bin",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "db",
        url: "https://openai.com/db",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "database",
        url: "https://openai.com/database",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "inc",
        url: "https://openai.com/inc",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: "log",
        url: "https://openai.com/log",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "sql",
        url: "https://openai.com/sql",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
      {
        path: ".htaccess",
        url: "https://openai.com/.htaccess",
        status: 403,
        type: "forbidden",
        interesting: false,
      },
    ],
    interesting_findings: [
      {
        path: "administrator",
        url: "https://openai.com/administrator",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "login",
        url: "https://openai.com/login",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "admin",
        url: "https://openai.com/admin",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "phpmyadmin",
        url: "https://openai.com/phpmyadmin",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "api",
        url: "https://openai.com/api",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "config",
        url: "https://openai.com/config",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "adminer",
        url: "https://openai.com/adminer",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "api/v2",
        url: "https://openai.com/api/v2",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "test",
        url: "https://openai.com/test",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "api/v1",
        url: "https://openai.com/api/v1",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "wp-admin",
        url: "https://openai.com/wp-admin",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "configuration",
        url: "https://openai.com/configuration",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "secret",
        url: "https://openai.com/secret",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "backup",
        url: "https://openai.com/backup",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: ".env",
        url: "https://openai.com/.env",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: ".git",
        url: "https://openai.com/.git",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "private",
        url: "https://openai.com/private",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "testing",
        url: "https://openai.com/testing",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "logs",
        url: "https://openai.com/logs",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "error_log",
        url: "https://openai.com/error_log",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "db",
        url: "https://openai.com/db",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "database",
        url: "https://openai.com/database",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
      {
        path: "log",
        url: "https://openai.com/log",
        status: 403,
        type: "forbidden",
        interesting: true,
      },
    ],
    total_checked: 66,
  },
  tech_results: {
    server: "cloudflare",
    cms: "WordPress",
    technologies: [
      {
        name: "cloudflare",
        category: "Web Server",
        source: "Header",
      },
      {
        name: "WordPress",
        category: "CMS",
        source: "Path: /wp-login.php",
      },
      {
        name: "Joomla",
        category: "CMS",
        source: "Path: /administrator/",
      },
      {
        name: "Drupal",
        category: "CMS",
        source: "Path: /user/login",
      },
      {
        name: "Magento",
        category: "CMS",
        source: "Path: /admin/",
      },
    ],
    javascript_libraries: [],
  },
};

export default function ScanDetailsPage() {
  const { type, id } = useParams();

  // Yahan par tum future me Redux ya API se data fetch kar sakte ho using 'id' aur 'type'
  // const [data, setData] = useState(null);
  // useEffect(() => { fetch(`/api/scan/${type}/${id}`) }, [id, type]);

  if (type === "web") {
    // Agar hume API se data pass karna hota toh hum prop me bhejte: <ScanRes data={data} />
    // Lekin abhi ke liye tumhare ScanRes me static data hai, toh sirf component render karo.
    return <ScanRes data={data} />;
  }

  if (type === "vuln") {
    return <SecurityReportDashboard SCAN_DATA={SCAN_DATA} />;
  }
  return <Navigate to="/" replace />;
}
